# Generated by Django 5.0.6 on 2024-07-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
